ARG version
FROM almalinux:${version}
FROM almalinux:9
# ARG course="Devops" \
#     duration="120hrs" \
#     name="Hari"
ENV course="Devops" \
    duration="120hrs" \
    name="Hari"
# ENV course=$course
RUN echo "course:$course, duration:$duration, name:$name, version:$version"
CMD ["sleep","100"]